# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento-ubuntu-24.04-local"
  config.vm.box_url = "file:///C:/Users/zazhigina/Downloads/ubuntu-24.04"
  config.vm.boot_timeout = 500
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
    vb.linked_clone = true
  end

  config.vm.define "nfss" do |nfss|
    nfss.vm.hostname = "nfss"
    nfss.vm.network "private_network", ip: "192.168.50.10"

    nfss.vm.provider "virtualbox" do |vb|
      vb.name = "nfs-nfss"
    end

    nfss.vm.provision "shell", path: "nfss_script.sh", privileged: true
  end

  config.vm.define "nfsc" do |nfsc|
    nfsc.vm.hostname = "nfsc"
    nfsc.vm.network "private_network", ip: "192.168.50.11"

    nfsc.vm.provider "virtualbox" do |vb|
      vb.name = "nfs-nfsc"
    end

    nfsc.vm.provision "shell", path: "nfsc_script.sh", privileged: true
  end
end
