---
- name: reload sysctl
  ansible.builtin.command: sysctl -p /etc/sysctl.d/99-elasticsearch.conf

- name: restart elasticsearch
  ansible.builtin.service:
    name: elasticsearch
    state: restarted

- name: restart logstash
  ansible.builtin.service:
    name: logstash
    state: restarted

- name: restart kibana
  ansible.builtin.service:
    name: kibana
    state: restarted
