services:
  redmine:
    build:
      context: ./redmine
    image: task-14-redmine-bleuclair:6.0
    depends_on:
      - db
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine_password
      REDMINE_SECRET_KEY_BASE: task_14_redmine_secret_key_base
    ports:
      - "3000:3000"
    volumes:
      - redmine_files:/usr/src/redmine/files

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: redmine
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: redmine_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  redmine_files:
