# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINES = {
  :nginx_bool => { :hostname => "nginx-bool", :ip => "10.11.0.10", :memory => 1024, :http_host_port => 4881 },
  :nginx_port => { :hostname => "nginx-port", :ip => "10.11.0.11", :memory => 1024, :http_host_port => 4882 },
  :nginx_module => { :hostname => "nginx-module", :ip => "10.11.0.12", :memory => 1024, :http_host_port => 4883 },
  :ns01 => { :hostname => "ns01", :ip => "10.11.0.20", :memory => 1024 },
  :client => { :hostname => "client", :ip => "10.11.0.21", :memory => 768 }
}

Vagrant.configure("2") do |config|
  config.vm.box = "almalinux/9"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.boot_timeout = 1200
  config.ssh.insert_key = false
  config.ssh.keep_alive = true

  MACHINES.each_with_index do |(name, machine), index|
    config.vm.define name do |box|
      box.vm.hostname = machine[:hostname]
      box.vm.network "forwarded_port",
        id: "ssh",
        guest: 22,
        host: 2450 + index,
        host_ip: "0.0.0.0",
        auto_correct: false
      box.ssh.host = ENV.fetch("VAGRANT_WSL_HOST_IP", "127.0.0.1")
      box.vm.network "private_network",
        ip: machine[:ip],
        netmask: "255.255.255.0",
        virtualbox__intnet: "task11-selinux"

      if machine.key?(:http_host_port)
        box.vm.network "forwarded_port",
          guest: 4881,
          host: machine[:http_host_port],
          host_ip: "127.0.0.1",
          auto_correct: false
      end

      box.vm.provider "virtualbox" do |vb|
        vb.name = "task-11-#{machine[:hostname]}"
        vb.memory = machine[:memory]
        vb.cpus = 1
      end
    end
  end
end
