[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_user=vagrant
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=/home/zazhigina/.vagrant.d/insecure_private_key

[routers]
inetRouter ansible_host=172.31.192.1 ansible_port=2260
centralRouter ansible_host=192.168.60.11
inetRouter2 ansible_host=192.168.60.13

[servers]
centralServer ansible_host=192.168.60.12

[all_hosts:children]
routers
servers
