# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINES = {
  :inetRouter => {
    :box_name => "centos/7",
    :hostname => "inetRouter",
    :mgmt_ip => "192.168.100.10",
    :memory => 512,
    :net => [
      { adapter: 2, auto_config: false, virtualbox__intnet: "router-net" },
      { adapter: 3, auto_config: false, virtualbox__intnet: "router-net" }
    ]
  },
  :centralRouter => {
    :box_name => "centos/7",
    :hostname => "centralRouter",
    :mgmt_ip => "192.168.100.11",
    :memory => 512,
    :net => [
      { adapter: 2, auto_config: false, virtualbox__intnet: "router-net" },
      { adapter: 3, auto_config: false, virtualbox__intnet: "router-net" },
      { ip: "192.168.255.9", adapter: 6, netmask: "255.255.255.252", virtualbox__intnet: "office1-central" }
    ]
  },
  :office1Router => {
    :box_name => "centos/7",
    :hostname => "office1Router",
    :mgmt_ip => "192.168.100.20",
    :memory => 512,
    :net => [
      { ip: "192.168.255.10", adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "office1-central" },
      { adapter: 3, auto_config: false, virtualbox__intnet: "vlan1" },
      { adapter: 4, auto_config: false, virtualbox__intnet: "vlan1" },
      { adapter: 5, auto_config: false, virtualbox__intnet: "vlan2" },
      { adapter: 6, auto_config: false, virtualbox__intnet: "vlan2" }
    ]
  },
  :testClient1 => {
    :box_name => "centos/7",
    :hostname => "testClient1",
    :mgmt_ip => "192.168.100.21",
    :memory => 384,
    :net => [
      { adapter: 2, auto_config: false, virtualbox__intnet: "testLAN" }
    ]
  },
  :testServer1 => {
    :box_name => "centos/7",
    :hostname => "testServer1",
    :mgmt_ip => "192.168.100.22",
    :memory => 384,
    :net => [
      { adapter: 2, auto_config: false, virtualbox__intnet: "testLAN" }
    ]
  },
  :testClient2 => {
    :box_name => "ubuntu/jammy64",
    :hostname => "testClient2",
    :mgmt_ip => "192.168.100.31",
    :memory => 512,
    :net => [
      { adapter: 2, auto_config: false, virtualbox__intnet: "testLAN" }
    ]
  },
  :testServer2 => {
    :box_name => "ubuntu/jammy64",
    :hostname => "testServer2",
    :mgmt_ip => "192.168.100.32",
    :memory => 512,
    :net => [
      { adapter: 2, auto_config: false, virtualbox__intnet: "testLAN" }
    ]
  }
}.freeze

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.boot_timeout = 1200
  config.ssh.insert_key = false
  config.ssh.keep_alive = true

  MACHINES.each_with_index do |(name, machine), index|
    config.vm.define name do |box|
      box.vm.box = machine[:box_name]
      box.vm.hostname = machine[:hostname]
      box.vm.network "forwarded_port",
        id: "ssh",
        guest: 22,
        host: 2400 + index,
        host_ip: "0.0.0.0",
        auto_correct: false
      box.ssh.host = ENV.fetch("VAGRANT_WSL_HOST_IP", "127.0.0.1")

      machine[:net].each do |ipconf|
        box.vm.network "private_network", **ipconf
      end

      box.vm.network "private_network",
        ip: machine[:mgmt_ip],
        adapter: 8,
        netmask: "255.255.255.0"

      box.vm.provision "shell", inline: <<-SHELL
        set -eux
        if command -v yum >/dev/null 2>&1; then
          sed -i 's/^mirrorlist=/#mirrorlist=/g' /etc/yum.repos.d/CentOS-Base.repo
          sed -i 's|^#baseurl=http://mirror.centos.org/centos/$releasever|baseurl=http://vault.centos.org/7.9.2009|g' /etc/yum.repos.d/CentOS-Base.repo
          yum makecache -y
        else
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y python3 sudo
        fi
      SHELL

      box.vm.provider "virtualbox" do |vb|
        vb.name = "task-25-#{name}"
        vb.memory = machine[:memory]
        vb.cpus = 1
      end
    end
  end

end
