---
- name: Disable ufw service
  service:
    name: ufw
    state: stopped
    enabled: false
  failed_when: false

- name: Install base packages
  apt:
    name:
      - curl
      - gnupg
      - iproute2
      - netplan.io
      - traceroute
    state: present
    update_cache: true
