[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_user=vagrant
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=/home/zazhigina/.vagrant.d/insecure_private_key

[routers]
inetRouter ansible_host=192.168.50.10
centralRouter ansible_host=192.168.50.11
office1Router ansible_host=192.168.50.20
office2Router ansible_host=192.168.50.30

[servers]
centralServer ansible_host=192.168.50.12
office1Server ansible_host=192.168.50.21
office2Server ansible_host=192.168.50.31

[all_hosts:children]
routers
servers
