[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_user=vagrant
ansible_ssh_private_key_file=/home/zazhigina/.vagrant.d/insecure_private_key
dns_server_ip=10.11.0.20
dns_client_ip=10.11.0.21

[nginx]
nginx_bool ansible_host=172.31.192.1 ansible_port=2450 mgmt_ip=10.11.0.10 selinux_nginx_method=boolean host_http_port=4881
nginx_port ansible_host=172.31.192.1 ansible_port=2451 mgmt_ip=10.11.0.11 selinux_nginx_method=port host_http_port=4882
nginx_module ansible_host=172.31.192.1 ansible_port=2452 mgmt_ip=10.11.0.12 selinux_nginx_method=module host_http_port=4883

[dns_servers]
ns01 ansible_host=172.31.192.1 ansible_port=2453 mgmt_ip=10.11.0.20

[dns_clients]
client ansible_host=172.31.192.1 ansible_port=2454 mgmt_ip=10.11.0.21
