# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINES = {
  :pam => {
    :box_name => "bento-ubuntu-24.04-local",
    :box_url => "file:///C:/Users/zazhigina/Downloads/ubuntu-24.04",
    :cpus => 2,
    :memory => 1024,
    :ip => "192.168.57.10"
  }
}

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true

  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_url = boxconfig[:box_url]
      box.vm.hostname = boxname.to_s
      box.vm.network "private_network", ip: boxconfig[:ip]
      box.vm.network "forwarded_port", id: "ssh", guest: 22, host: 2222, host_ip: "0.0.0.0", auto_correct: true
      box.ssh.host = ENV.fetch("VAGRANT_WSL_HOST_IP", "127.0.0.1")

      box.vm.provider "virtualbox" do |vb|
        vb.name = "task-16-pam"
        vb.memory = boxconfig[:memory]
        vb.cpus = boxconfig[:cpus]
      end

      box.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/playbook.yml"
        ansible.compatibility_mode = "2.0"
      end
    end
  end
end
