server {
    listen 9001 default_server;
    server_name _;

    root /var/www/web-report;
    index index.html;

    access_log /var/log/nginx/web-report-access.log;
    error_log /var/log/nginx/web-report-error.log warn;

    location / {
        try_files $uri $uri/ =404;
    }

    location /app-error {
        return 500;
    }
}
