[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_user=vagrant
ansible_ssh_private_key_file=/home/zazhigina/.vagrant.d/insecure_private_key

[routers]
inetRouter ansible_host=172.31.192.1 ansible_port=2400 bond_ip=192.168.255.1
centralRouter ansible_host=192.168.100.11 bond_ip=192.168.255.2
office1Router ansible_host=192.168.100.20

[vlan1]
testClient1 ansible_host=192.168.100.21 vlan_id=1 vlan_ip=10.10.10.254
testServer1 ansible_host=192.168.100.22 vlan_id=1 vlan_ip=10.10.10.1

[vlan2]
testClient2 ansible_host=192.168.100.31 vlan_id=2 vlan_ip=10.10.10.254
testServer2 ansible_host=192.168.100.32 vlan_id=2 vlan_ip=10.10.10.1

[vlan_hosts:children]
vlan1
vlan2
