[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_user=vagrant
ansible_python_interpreter=/usr/bin/python3
ansible_become_timeout=30

[webservers]
web ansible_host=172.31.192.1 ansible_port=2200 ansible_ssh_private_key_file=/home/zazhigina/.vagrant.d/insecure_private_key

[logservers]
log ansible_host=172.31.192.1 ansible_port=2201 ansible_ssh_private_key_file=/home/zazhigina/.vagrant.d/insecure_private_key

[clients]
client ansible_host=172.31.192.1 ansible_port=2202 ansible_ssh_private_key_file=/home/zazhigina/.vagrant.d/insecure_private_key

[elkservers]
elk ansible_host=172.31.192.1 ansible_port=2203 ansible_ssh_private_key_file=/home/zazhigina/.vagrant.d/insecure_private_key
