# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINES = {
  :mysqlmaster => { :hostname => "mysqlmaster", :ip => "192.168.56.30", :memory => 1536 },
  :mysqlslave => { :hostname => "mysqlslave", :ip => "192.168.56.31", :memory => 1536 }
}

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.boot_timeout = 1200
  config.ssh.insert_key = false
  config.ssh.keep_alive = true

  MACHINES.each_with_index do |(name, machine), index|
    config.vm.define name do |box|
      box.vm.hostname = machine[:hostname]
      box.vm.network "forwarded_port",
        id: "ssh",
        guest: 22,
        host: 2430 + index,
        host_ip: "0.0.0.0",
        auto_correct: false
      box.ssh.host = ENV.fetch("VAGRANT_WSL_HOST_IP", "127.0.0.1")
      box.vm.network "private_network", ip: machine[:ip], netmask: "255.255.255.0"

      box.vm.provider "virtualbox" do |vb|
        vb.name = "task-28-#{machine[:hostname]}"
        vb.memory = machine[:memory]
        vb.cpus = 1
      end
    end
  end

end
