# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINES = {
  :ipa => { :hostname => "ipa.otus.lan", :ip => "192.168.56.10", :memory => 4096 },
  :client1 => { :hostname => "client1.otus.lan", :ip => "192.168.56.11", :memory => 1024 },
  :client2 => { :hostname => "client2.otus.lan", :ip => "192.168.56.12", :memory => 1024 }
}.freeze

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8s"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.boot_timeout = 1800
  config.ssh.insert_key = false
  config.ssh.keep_alive = true

  MACHINES.each_with_index do |(name, machine), index|
    config.vm.define name do |box|
      box.vm.hostname = machine[:hostname]
      box.vm.network "forwarded_port",
        id: "ssh",
        guest: 22,
        host: 2410 + index,
        host_ip: "0.0.0.0",
        auto_correct: false
      box.ssh.host = ENV.fetch("VAGRANT_WSL_HOST_IP", "127.0.0.1")

      box.vm.network "private_network",
        ip: machine[:ip],
        netmask: "255.255.255.0"

      box.vm.provision "shell", inline: <<-SHELL
        set -eux
        sed -i 's/^mirrorlist=/#mirrorlist=/g' /etc/yum.repos.d/CentOS-Stream-*.repo
        sed -i 's|^#baseurl=http://mirror.centos.org/$contentdir/$stream|baseurl=http://vault.centos.org/8-stream|g' /etc/yum.repos.d/CentOS-Stream-*.repo
        dnf install -y python3 python3-libselinux
      SHELL

      box.vm.provider "virtualbox" do |vb|
        vb.name = "task-26-#{name}"
        vb.memory = machine[:memory]
        vb.cpus = 1
      end
    end
  end

end
