# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINES = {
  :node1 => { :hostname => "node1", :ip => "10.29.0.10", :memory => 1536, :cpus => 2 },
  :node2 => { :hostname => "node2", :ip => "10.29.0.11", :memory => 1536, :cpus => 1 },
  :barman => { :hostname => "barman", :ip => "10.29.0.12", :memory => 1536, :cpus => 1 }
}

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.boot_timeout = 1800
  config.ssh.insert_key = false
  config.ssh.keep_alive = true

  MACHINES.each_with_index do |(name, machine), index|
    config.vm.define name do |box|
      box.vm.hostname = machine[:hostname]
      box.vm.network "forwarded_port",
        id: "ssh",
        guest: 22,
        host: [2440, 2464, 2465][index],
        host_ip: "0.0.0.0",
        auto_correct: false
      box.ssh.host = ENV.fetch("VAGRANT_WSL_HOST_IP", "127.0.0.1")
      box.vm.network "private_network",
        ip: machine[:ip],
        netmask: "255.255.255.0",
        virtualbox__intnet: "task29-pgnet"

      box.vm.provision "shell", inline: <<-SHELL
        set -eux
        apt-get update
        DEBIAN_FRONTEND=noninteractive apt-get install -y python3 sudo
      SHELL

      box.vm.provider "virtualbox" do |vb|
        vb.name = "task-29-#{machine[:hostname]}"
        vb.memory = machine[:memory]
        vb.cpus = machine[:cpus]
      end
    end
  end

end
