---
- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted

- name: load audit rules
  ansible.builtin.command: augenrules --load
  changed_when: false
