[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=NUL -o ControlMaster=no -o ControlPersist=no'
ansible_ssh_args='-C -o ControlMaster=no -o ControlPersist=no -o PreferredAuthentications=publickey -o ServerAliveInterval=15 -o ServerAliveCountMax=3'
ansible_user=vagrant
ansible_ssh_private_key_file=C:/Users/zazhigina/.vagrant.d/insecure_private_key
ansible_ssh_executable=/mnt/c/Users/zazhigina/administrator-linux-professional/task-29-postgresql-replication/ansible/ssh-wrapper.sh
postgres_version=14
replicator_user=replication
replicator_password=Otus2022!
barman_db_user=barman
barman_db_password=Otus2022!
master_ip=10.29.0.10
slave_ip=10.29.0.11
barman_ip=10.29.0.12

[postgres_master]
node1 ansible_host=127.0.0.1 ansible_port=2440 pg_role=master pg_ip=10.29.0.10

[postgres_standby]
node2 ansible_host=127.0.0.1 ansible_port=2464 pg_role=standby pg_ip=10.29.0.11

[barman_server]
barman ansible_host=127.0.0.1 ansible_port=2465 pg_role=barman pg_ip=10.29.0.12

[postgres_servers:children]
postgres_master
postgres_standby
