# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINES = {
  :web => {
    :box_name => "almalinux/9",
    :box_url => "file:///C:/Users/zazhigina/Downloads/alma-9",
    :hostname => "web",
    :ip => "192.168.57.10",
    :memory => 2048,
    :cpus => 2
  },
  :log => {
    :box_name => "almalinux/9",
    :box_url => "file:///C:/Users/zazhigina/Downloads/alma-9",
    :hostname => "log",
    :ip => "192.168.57.11",
    :memory => 2048,
    :cpus => 2
  },
  :client => {
    :box_name => "almalinux/9",
    :box_url => "file:///C:/Users/zazhigina/Downloads/alma-9",
    :hostname => "client",
    :ip => "192.168.57.12",
    :memory => 1024,
    :cpus => 2
  },
  :elk => {
    :box_name => "almalinux/9",
    :box_url => "file:///C:/Users/zazhigina/Downloads/alma-9",
    :hostname => "elk",
    :ip => "192.168.57.13",
    :memory => 6144,
    :cpus => 2
  }
}

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.boot_timeout = 1200
  config.ssh.insert_key = false
  config.ssh.keep_alive = true

  MACHINES.each do |name, machine|
    config.vm.define name do |box|
      box.vm.box = machine[:box_name]
      box.vm.box_url = machine[:box_url]
      box.vm.hostname = machine[:hostname]
      box.vm.network "private_network", ip: machine[:ip]
      box.vm.network "forwarded_port", id: "ssh", guest: 22, host: 2200 + MACHINES.keys.index(name), host_ip: "0.0.0.0", auto_correct: false
      box.ssh.host = ENV.fetch("VAGRANT_WSL_HOST_IP", "127.0.0.1")

      if name == :web
        box.vm.network "forwarded_port", guest: 80, host: 8081, auto_correct: true
      elsif name == :elk
        box.vm.network "forwarded_port", guest: 5601, host: 5601, auto_correct: true
        box.vm.network "forwarded_port", guest: 9200, host: 9200, auto_correct: true
      end

      box.vm.provider "virtualbox" do |vb|
        vb.name = "task-17-#{name}"
        vb.memory = machine[:memory]
        vb.cpus = machine[:cpus]
      end
    end
  end
end
