[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_user=vagrant
ansible_python_interpreter=/usr/bin/python
ansible_ssh_private_key_file=/home/zazhigina/.vagrant.d/insecure_private_key

[dns_servers]
ns01 ansible_host=172.31.192.1 ansible_port=2390 dns_ip=192.168.90.10 dns_role=master
ns02 ansible_host=192.168.90.11 dns_ip=192.168.90.11 dns_role=slave

[dns_clients]
client ansible_host=192.168.90.15 dns_ip=192.168.90.15
client2 ansible_host=192.168.90.16 dns_ip=192.168.90.16

[all_hosts:children]
dns_servers
dns_clients
