# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINES = {
  :router1 => {
    :box_name => "generic/ubuntu2004",
    :hostname => "router1",
    :memory => 768,
    :cpus => 1,
    :mgmt_ip => "192.168.70.10",
    :net => [
      ["10.0.10.1", 2, "255.255.255.252", "r1-r2"],
      ["10.0.12.1", 3, "255.255.255.252", "r1-r3"],
      ["192.168.10.1", 4, "255.255.255.0", "net1"]
    ]
  },
  :router2 => {
    :box_name => "generic/ubuntu2004",
    :hostname => "router2",
    :memory => 768,
    :cpus => 1,
    :mgmt_ip => "192.168.70.11",
    :net => [
      ["10.0.10.2", 2, "255.255.255.252", "r1-r2"],
      ["10.0.11.2", 3, "255.255.255.252", "r2-r3"],
      ["192.168.20.1", 4, "255.255.255.0", "net2"]
    ]
  },
  :router3 => {
    :box_name => "generic/ubuntu2004",
    :hostname => "router3",
    :memory => 768,
    :cpus => 1,
    :mgmt_ip => "192.168.70.12",
    :net => [
      ["10.0.11.1", 2, "255.255.255.252", "r2-r3"],
      ["10.0.12.2", 3, "255.255.255.252", "r1-r3"],
      ["192.168.30.1", 4, "255.255.255.0", "net3"]
    ]
  }
}.freeze

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.boot_timeout = 1200
  config.ssh.insert_key = false
  config.ssh.keep_alive = true

  MACHINES.each_with_index do |(name, machine), index|
    config.vm.define name do |box|
      box.vm.box = machine[:box_name]
      box.vm.hostname = machine[:hostname]
      box.vm.network "forwarded_port",
        id: "ssh",
        guest: 22,
        host: 2370 + index,
        host_ip: "0.0.0.0",
        auto_correct: false
      box.ssh.host = ENV.fetch("VAGRANT_WSL_HOST_IP", "127.0.0.1")

      machine[:net].each do |ipconf|
        box.vm.network "private_network",
          ip: ipconf[0],
          adapter: ipconf[1],
          netmask: ipconf[2],
          virtualbox__intnet: ipconf[3]
      end

      box.vm.network "private_network",
        ip: machine[:mgmt_ip],
        adapter: 8,
        netmask: "255.255.255.0"

      box.vm.provision "shell", inline: <<-SHELL
        set -eux
        apt-get update
        DEBIAN_FRONTEND=noninteractive apt-get install -y python3 sudo
      SHELL

      box.vm.provider "virtualbox" do |vb|
        vb.name = "task-22-#{name}"
        vb.memory = machine[:memory]
        vb.cpus = machine[:cpus]
      end
    end
  end
end
